rm -f ./wp-admin.php
rm -f ./index.php
rm -f ./old-index.php
rm -f ./hapygeslyegss.php
rm -f ./readme.html
rm -f ./wp-admin/Ymlvdml0YWwuYWljb2RlLXRlc3QuYXJ0a.txt
rm -f ./wp-admin/Ymlvdml0YWwuYWljb2RlLXRlc3QuYXJ0.txt
rm -f ./wp-admin/about.php
rm -f ./3index.php
rm -f ./wp-includes/Requests/new_default_options.php
rm -f ./wp-content/uploads/wc-logs/index.html
rm -f ./wp-content/uploads/woocommerce_uploads/index.html
rm -rf ./wp-content/mu-plugins-old
rm -f ./admin.php
rm -f ./wikindex.php
rm -f ./wp-content/themes/woodmart/changelog.html
rm -f ./wp-content/languages/continents-cities-es_ES.mo
rm -f ./wp-content/languages/admin-network-es_ES.mo
rm -f ./wp-content/languages/es_ES.po
rm -f ./wp-content/languages/continents-cities-es_ES.po
rm -f ./wp-content/languages/admin-es_ES.mo
rm -f ./wp-content/languages/admin-network-es_ES.po
rm -f ./wp-content/languages/es_ES.mo